name: CharacterCard
version: '1.3.0-experimental-2'
main: net.lordofthetimes.characterCard.CharacterCard
api-version: '1.21'
author: LordofTheTimes
dependencies:
  server:
    Essentials:
      load: BEFORE
      required: false
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    LandsAPI:
      load: BEFORE
      required: false
permissions:
  charactercard.character.clear.others:
    description: Allows clearing the character card for other players