name: CharacterCard
version: '1.1.1'
main: net.lordofthetimes.characterCard.CharacterCard
api-version: '1.21'
author: LordofTheTimes
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    LandsAPI:
      load: BEFORE
      required: false