name: CharacterCard
version: '1.0-SNAPSHOT'
main: net.lordofthetimes.characterCard.CharacterCard
api-version: '1.21'
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
softdepend:
  - Lands