name: Test Discord
on:
  workflow_dispatch:
    inputs:
      changelog:
        description: 'Changelog'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        run: |
          CONTENT="## Character Cards TEST\n\n${{ github.event.inputs.changelog }}\n\n**You can download this version [here](https://modrinth.com/plugin/character-cards/version/TEST)!**"
          jq -n --arg content "$CONTENT" '{"content": $content, "flags": 4}' | \
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d @-
