name: Release Modrinth
on:
  release:
    types: [published]

jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Modrinth
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          CHANGELOG=$(cat CHANGELOG.md)
          
          DATA=$(jq -n \
            --arg version "$VERSION" \
            --arg changelog "## Character Cards ${VERSION}
  
            ${CHANGELOG}
            
            **To update the plugin, just delete the old version and drag the new one into the plugins folder. I recommend to first boot up test server and see config changes**
            If you find any issues or want to suggest features, please open an issue on my github repo [--> here <--](https://github.com/lordofthetimes/CharacterCards/issues)" \
            '{
          "name": $version,
          "version_number": $version,
          "changelog": $changelog,
          "game_versions": ["1.21.x", "26.1.x"],
          "version_type": "release",
          "loaders": ["paper", "purpur"],
          "featured": true,
          "project_id": "bmeFJq7B",
          "file_parts": ["jar"]
          }')
            
            curl -X POST "https://api.modrinth.com/v2/version" \
          -H "Authorization: ${{ secrets.MODRINTH_SECRET }}" \
            -F "data=$DATA" \
            -F "jar=@build/libs/CharacterCard-${VERSION}.jar"