on:
  release:
    types: [published]
jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from release
        run: |
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          mkdir -p build/libs
          gh release download "${VERSION}" --dir build/libs

      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: bmeFJq7B
          modrinth-token: ${{ secrets.MODRINTH_SECRET }}

          files: build/libs/CharacterCard-${{ env.VERSION }}.jar
          version: ${{ env.VERSION }}
          version-type: release

          loaders: |
            paper
            purpur

          game-versions: |
            1.21.x
            26.1.x

          changelog: ${{ github.event.release.body }}


  discord:
    runs-on: ubuntu-latest
    needs: modrinth
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          VERSION="${{ env.VERSION }}"
          jq -n --arg content "## Character Cards ${VERSION}

          ${CHANGELOG}

          **You can download this version [here](https://modrinth.com/plugin/character-cards/version/${VERSION})!**" \
          '{"content": $content, "flags": 4}' | \
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d @-