name: Publish Release
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version from gradle.properties
        run: echo "VERSION=$(grep 'version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Create release changelog
        run: |
            cat > RELEASE_CHANGELOG.md <<EOF
            ## Character Cards ${VERSION}
            
            $(cat CHANGELOG.md)
            
            **To update the plugin, just delete the old version and drag the new one into the plugins folder. I recommend to first boot up test server and see config changes**
            
            If you find any issues or want to suggest features, please open an issue on my github repo [--> here <--](https://github.com/lordofthetimes/CharacterCards/issues)
            EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          body_path: RELEASE_CHANGELOG.md
          files: build/libs/CharacterCard-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: build/libs/CharacterCard-${{ env.VERSION }}.jar
